- name: Set up Flask app servers
  hosts: webservers
  become: yes
  tasks:
    - name: Install Python and Flask
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes

    - name: Install Flask via pip
      pip:
        name: flask

    - name: Clone the application repo
      git:
        repo: https://github.com/patrikarlos/NSO_A2.git
        dest: /home/ubuntu/app
        version: main

    - name: Run Flask app
      shell: |
        FLASK_APP=/home/ubuntu/app/application2.py nohup flask run --host=0.0.0.0 --port=5000 &
      args:
        executable: /bin/bash
      async: 30
      poll: 0

- name: Set up HAproxy
  hosts: haproxy
  become: yes
  tasks:
    - name: Install HAproxy
      apt:
        name: haproxy
        update_cache: yes

    - name: Deploy HAproxy config
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart haproxy

  handlers:
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
